openapi: 3.0.3
info:
  title: FoodTec PizzaBolis API
  version: "1.0.0"
servers:
  - url: http://localhost:8080/apiclient # Proxy base
paths:
  /menu:
    get:
      summary: Export menu
      responses:
        "200":
          description: Menu JSON
  /validateOrder:
    post:
      summary: Validate order
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Validation result
  /acceptOrder:
    post:
      summary: Accept order
      parameters:
        - in: header
          name: Idempotency-Key
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Confirmation
